export const allcategorydata=[
    {
        id:1,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-tOjbkXk29RLlJq-xcqM3OHidAH9a_NZZ0-8rGW2Jeh2kXu8bDiUznXP_MQTkm8yO8T0&usqp=CAU"
    },
    {
        id:2,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvktLPpmnt698pjT-hyoIYqnawBkUH0T0Shg&s"
    },
    {
        id:3,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6noUuJtFub0kjiEkBICbEcz2R98-BY7oHBA&s"
    },

    {
        id:4,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-tOjbkXk29RLlJq-xcqM3OHidAH9a_NZZ0-8rGW2Jeh2kXu8bDiUznXP_MQTkm8yO8T0&usqp=CAU"
    },
    {
        id:5,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvktLPpmnt698pjT-hyoIYqnawBkUH0T0Shg&s"
    },
    {
        id:6,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6noUuJtFub0kjiEkBICbEcz2R98-BY7oHBA&s"
    },
    {
        id:7,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-tOjbkXk29RLlJq-xcqM3OHidAH9a_NZZ0-8rGW2Jeh2kXu8bDiUznXP_MQTkm8yO8T0&usqp=CAU"
    },
    {
        id:8,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvktLPpmnt698pjT-hyoIYqnawBkUH0T0Shg&s"
    },
    {
        id:9,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6noUuJtFub0kjiEkBICbEcz2R98-BY7oHBA&s"
    },

    {
        id:10,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvktLPpmnt698pjT-hyoIYqnawBkUH0T0Shg&s"
    },
    {
        id:11,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6noUuJtFub0kjiEkBICbEcz2R98-BY7oHBA&s"
    },
    {
        id:12,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-tOjbkXk29RLlJq-xcqM3OHidAH9a_NZZ0-8rGW2Jeh2kXu8bDiUznXP_MQTkm8yO8T0&usqp=CAU"
    },
    {
        id:13,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvktLPpmnt698pjT-hyoIYqnawBkUH0T0Shg&s"
    },
    {
        id:14,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6noUuJtFub0kjiEkBICbEcz2R98-BY7oHBA&s"
    },

    {
        id:15,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvktLPpmnt698pjT-hyoIYqnawBkUH0T0Shg&s"
    },
    {
        id:16,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6noUuJtFub0kjiEkBICbEcz2R98-BY7oHBA&s"
    },
    {
        id:17,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-tOjbkXk29RLlJq-xcqM3OHidAH9a_NZZ0-8rGW2Jeh2kXu8bDiUznXP_MQTkm8yO8T0&usqp=CAU"
    },
    {
        id:18,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvktLPpmnt698pjT-hyoIYqnawBkUH0T0Shg&s"
    },
    {
        id:19,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6noUuJtFub0kjiEkBICbEcz2R98-BY7oHBA&s"
    },
]
